# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coal_price_manage.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CoalPrice(object):
    def setupUi(self, CoalPrice):
        CoalPrice.setObjectName("CoalPrice")
        CoalPrice.resize(760, 425)
        self.selectDate = QtWidgets.QPushButton(CoalPrice)
        self.selectDate.setGeometry(QtCore.QRect(64, 100, 81, 23))
        self.selectDate.setObjectName("selectDate")
        self.coal_sorts = QtWidgets.QComboBox(CoalPrice)
        self.coal_sorts.setGeometry(QtCore.QRect(160, 140, 131, 21))
        self.coal_sorts.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.coal_sorts.setObjectName("coal_sorts")
        self.coal_sell_price_display = QtWidgets.QLabel(CoalPrice)
        self.coal_sell_price_display.setGeometry(QtCore.QRect(140, 250, 101, 20))
        self.coal_sell_price_display.setObjectName("coal_sell_price_display")
        self.coal_sort_label = QtWidgets.QLabel(CoalPrice)
        self.coal_sort_label.setGeometry(QtCore.QRect(90, 140, 59, 16))
        self.coal_sort_label.setObjectName("coal_sort_label")
        self.coal_purchase_price_display = QtWidgets.QLabel(CoalPrice)
        self.coal_purchase_price_display.setGeometry(QtCore.QRect(140, 210, 101, 20))
        self.coal_purchase_price_display.setObjectName("coal_purchase_price_display")
        self.purchase_compute_unit = QtWidgets.QComboBox(CoalPrice)
        self.purchase_compute_unit.setGeometry(QtCore.QRect(415, 210, 69, 22))
        self.purchase_compute_unit.setObjectName("purchase_compute_unit")
        self.coal_purchase_price_label = QtWidgets.QLabel(CoalPrice)
        self.coal_purchase_price_label.setGeometry(QtCore.QRect(385, 210, 31, 16))
        self.coal_purchase_price_label.setObjectName("coal_purchase_price_label")
        self.date_value_content = QtWidgets.QLineEdit(CoalPrice)
        self.date_value_content.setGeometry(QtCore.QRect(160, 100, 151, 20))
        self.date_value_content.setObjectName("date_value_content")
        self.ok = QtWidgets.QPushButton(CoalPrice)
        self.ok.setGeometry(QtCore.QRect(300, 340, 81, 23))
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(CoalPrice)
        self.cancel.setGeometry(QtCore.QRect(410, 340, 81, 23))
        self.cancel.setObjectName("cancel")
        self.purchase_price_check_box = QtWidgets.QCheckBox(CoalPrice)
        self.purchase_price_check_box.setGeometry(QtCore.QRect(80, 210, 71, 16))
        self.purchase_price_check_box.setObjectName("purchase_price_check_box")
        self.sell_price_check_box = QtWidgets.QCheckBox(CoalPrice)
        self.sell_price_check_box.setGeometry(QtCore.QRect(80, 250, 71, 16))
        self.sell_price_check_box.setObjectName("sell_price_check_box")
        self.purchase_price_input = QtWidgets.QLineEdit(CoalPrice)
        self.purchase_price_input.setGeometry(QtCore.QRect(305, 210, 71, 20))
        self.purchase_price_input.setObjectName("purchase_price_input")
        self.sell_price_input = QtWidgets.QLineEdit(CoalPrice)
        self.sell_price_input.setGeometry(QtCore.QRect(310, 250, 71, 20))
        self.sell_price_input.setObjectName("sell_price_input")
        self.coal_sell_price_label = QtWidgets.QLabel(CoalPrice)
        self.coal_sell_price_label.setGeometry(QtCore.QRect(390, 250, 31, 16))
        self.coal_sell_price_label.setObjectName("coal_sell_price_label")
        self.sell_compute_unit = QtWidgets.QComboBox(CoalPrice)
        self.sell_compute_unit.setGeometry(QtCore.QRect(420, 250, 69, 22))
        self.sell_compute_unit.setObjectName("sell_compute_unit")
        self.purchase_price_change_label = QtWidgets.QLabel(CoalPrice)
        self.purchase_price_change_label.setGeometry(QtCore.QRect(250, 210, 41, 20))
        self.purchase_price_change_label.setObjectName("purchase_price_change_label")
        self.sell_price_change_label = QtWidgets.QLabel(CoalPrice)
        self.sell_price_change_label.setGeometry(QtCore.QRect(250, 250, 40, 20))
        self.sell_price_change_label.setObjectName("sell_price_change_label")

        self.retranslateUi(CoalPrice)
        self.selectDate.clicked.connect(CoalPrice.open_calendar)
        self.purchase_price_check_box.stateChanged['int'].connect(CoalPrice.on_purchase_price_check_box_selected)
        self.sell_price_check_box.stateChanged['int'].connect(CoalPrice.on_sell_price_check_box_selected)
        self.ok.clicked.connect(CoalPrice.accept)
        self.cancel.clicked.connect(CoalPrice.reject)
        self.coal_sorts.currentIndexChanged['int'].connect(CoalPrice.on_coal_sort_selected)
        QtCore.QMetaObject.connectSlotsByName(CoalPrice)

    def retranslateUi(self, CoalPrice):
        _translate = QtCore.QCoreApplication.translate
        CoalPrice.setWindowTitle(_translate("CoalPrice", "Dialog"))
        self.selectDate.setText(_translate("CoalPrice", "点击选择日期"))
        self.coal_sell_price_display.setText(_translate("CoalPrice", "这里动态显示售价"))
        self.coal_sort_label.setText(_translate("CoalPrice", "选择煤种"))
        self.coal_purchase_price_display.setText(_translate("CoalPrice", "这里动态显示进价"))
        self.coal_purchase_price_label.setText(_translate("CoalPrice", "单位"))
        self.ok.setText(_translate("CoalPrice", "确定更改"))
        self.cancel.setText(_translate("CoalPrice", "返回"))
        self.purchase_price_check_box.setText(_translate("CoalPrice", "进价"))
        self.sell_price_check_box.setText(_translate("CoalPrice", "售价"))
        self.coal_sell_price_label.setText(_translate("CoalPrice", "单位"))
        self.purchase_price_change_label.setText(_translate("CoalPrice", "变更为"))
        self.sell_price_change_label.setText(_translate("CoalPrice", "变更为"))

