# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ticket_price_manage.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ticket_Price(object):
    def setupUi(self, Ticket_Price):
        Ticket_Price.setObjectName("Ticket_Price")
        Ticket_Price.resize(897, 378)
        Ticket_Price.setFocusPolicy(QtCore.Qt.NoFocus)
        self.date_value_content = QtWidgets.QLineEdit(Ticket_Price)
        self.date_value_content.setGeometry(QtCore.QRect(130, 50, 151, 20))
        self.date_value_content.setObjectName("date_value_content")
        self.purchase_price_check_box = QtWidgets.QCheckBox(Ticket_Price)
        self.purchase_price_check_box.setGeometry(QtCore.QRect(50, 130, 111, 16))
        self.purchase_price_check_box.setObjectName("purchase_price_check_box")
        self.selectDate = QtWidgets.QPushButton(Ticket_Price)
        self.selectDate.setGeometry(QtCore.QRect(34, 50, 81, 23))
        self.selectDate.setObjectName("selectDate")
        self.cancel = QtWidgets.QPushButton(Ticket_Price)
        self.cancel.setGeometry(QtCore.QRect(380, 290, 81, 23))
        self.cancel.setObjectName("cancel")
        self.input_new_purchase_price_label = QtWidgets.QLabel(Ticket_Price)
        self.input_new_purchase_price_label.setGeometry(QtCore.QRect(70, 150, 81, 20))
        self.input_new_purchase_price_label.setObjectName("input_new_purchase_price_label")
        self.purchase_compute_unit = QtWidgets.QComboBox(Ticket_Price)
        self.purchase_compute_unit.setGeometry(QtCore.QRect(350, 150, 69, 22))
        self.purchase_compute_unit.setObjectName("purchase_compute_unit")
        self.sell_compute_unit = QtWidgets.QComboBox(Ticket_Price)
        self.sell_compute_unit.setGeometry(QtCore.QRect(350, 230, 69, 22))
        self.sell_compute_unit.setObjectName("sell_compute_unit")
        self.purchase_unit_label = QtWidgets.QLabel(Ticket_Price)
        self.purchase_unit_label.setGeometry(QtCore.QRect(320, 150, 31, 16))
        self.purchase_unit_label.setObjectName("purchase_unit_label")
        self.ticket_sorts = QtWidgets.QComboBox(Ticket_Price)
        self.ticket_sorts.setGeometry(QtCore.QRect(130, 90, 131, 21))
        self.ticket_sorts.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.ticket_sorts.setObjectName("ticket_sorts")
        self.ticket_sell_price_display = QtWidgets.QLabel(Ticket_Price)
        self.ticket_sell_price_display.setGeometry(QtCore.QRect(160, 210, 101, 20))
        self.ticket_sell_price_display.setObjectName("ticket_sell_price_display")
        self.ticket_purchase_price_display = QtWidgets.QLabel(Ticket_Price)
        self.ticket_purchase_price_display.setGeometry(QtCore.QRect(160, 130, 101, 20))
        self.ticket_purchase_price_display.setObjectName("ticket_purchase_price_display")
        self.ok = QtWidgets.QPushButton(Ticket_Price)
        self.ok.setGeometry(QtCore.QRect(270, 290, 81, 23))
        self.ok.setObjectName("ok")
        self.input_new_sellprice_label = QtWidgets.QLabel(Ticket_Price)
        self.input_new_sellprice_label.setGeometry(QtCore.QRect(70, 230, 91, 20))
        self.input_new_sellprice_label.setObjectName("input_new_sellprice_label")
        self.ticket_sort_label = QtWidgets.QLabel(Ticket_Price)
        self.ticket_sort_label.setGeometry(QtCore.QRect(60, 90, 59, 16))
        self.ticket_sort_label.setObjectName("ticket_sort_label")
        self.sell_price_check_box = QtWidgets.QCheckBox(Ticket_Price)
        self.sell_price_check_box.setGeometry(QtCore.QRect(50, 210, 91, 16))
        self.sell_price_check_box.setObjectName("sell_price_check_box")
        self.sell_unit_label = QtWidgets.QLabel(Ticket_Price)
        self.sell_unit_label.setGeometry(QtCore.QRect(320, 230, 31, 16))
        self.sell_unit_label.setObjectName("sell_unit_label")
        self.purchase_price_input = QtWidgets.QLineEdit(Ticket_Price)
        self.purchase_price_input.setGeometry(QtCore.QRect(240, 150, 71, 20))
        self.purchase_price_input.setObjectName("purchase_price_input")
        self.sell_price_input = QtWidgets.QLineEdit(Ticket_Price)
        self.sell_price_input.setGeometry(QtCore.QRect(240, 230, 71, 20))
        self.sell_price_input.setObjectName("sell_price_input")
        self.modify_detail_list = QtWidgets.QListView(Ticket_Price)
        self.modify_detail_list.setGeometry(QtCore.QRect(510, 50, 361, 271))
        self.modify_detail_list.setObjectName("modify_detail_list")
        self.modify_label = QtWidgets.QLabel(Ticket_Price)
        self.modify_label.setGeometry(QtCore.QRect(510, 20, 191, 20))
        self.modify_label.setObjectName("modify_label")

        self.retranslateUi(Ticket_Price)
        self.selectDate.clicked.connect(Ticket_Price.select_date)
        self.ticket_sorts.currentIndexChanged['int'].connect(Ticket_Price.select_ticket_sort)
        self.purchase_price_check_box.stateChanged['int'].connect(Ticket_Price.select_modify_purchase_price)
        self.sell_price_check_box.stateChanged['int'].connect(Ticket_Price.select_modify_sell_price)
        self.purchase_price_input.editingFinished.connect(Ticket_Price.input_new_purchase_price)
        self.purchase_compute_unit.currentIndexChanged['int'].connect(Ticket_Price.select_purchase_compute_unit)
        self.sell_compute_unit.currentIndexChanged['int'].connect(Ticket_Price.select_sell_compute_unit)
        self.sell_price_input.editingFinished.connect(Ticket_Price.input_new_sell_price)
        self.ok.clicked.connect(Ticket_Price.confirm_update)
        self.cancel.clicked.connect(Ticket_Price.reject)
        QtCore.QMetaObject.connectSlotsByName(Ticket_Price)

    def retranslateUi(self, Ticket_Price):
        _translate = QtCore.QCoreApplication.translate
        Ticket_Price.setWindowTitle(_translate("Ticket_Price", "票价管理"))
        self.purchase_price_check_box.setText(_translate("Ticket_Price", "勾选修改进价"))
        self.selectDate.setText(_translate("Ticket_Price", "点击选择日期"))
        self.cancel.setText(_translate("Ticket_Price", "返回"))
        self.input_new_purchase_price_label.setText(_translate("Ticket_Price", "输入新价格"))
        self.purchase_unit_label.setText(_translate("Ticket_Price", "单位"))
        self.ticket_sell_price_display.setText(_translate("Ticket_Price", "这里动态显示售价"))
        self.ticket_purchase_price_display.setText(_translate("Ticket_Price", "这里动态显示进价"))
        self.ok.setText(_translate("Ticket_Price", "确定更改"))
        self.input_new_sellprice_label.setText(_translate("Ticket_Price", "输入新价格"))
        self.ticket_sort_label.setText(_translate("Ticket_Price", "选择票种"))
        self.sell_price_check_box.setText(_translate("Ticket_Price", "勾选修改售价"))
        self.sell_unit_label.setText(_translate("Ticket_Price", "单位"))
        self.modify_label.setText(_translate("Ticket_Price", "修改项"))
